// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiblahxjywwlmqbfcdjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYmxhaHhqeXd3bG1xYmZjZGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDIyNDcsImV4cCI6MjA1OTU3ODI0N30.wq3JHY-biuayLcW0tkJsqKCk3Fo0UDnHZKhbsLruWfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);